project1-wiki/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.content_page, name="content_page"),
    path("search", views.show_search_results, name="show_search_results"),
    path("add", views.add_entry, name="add_entry"),
    path("edit", views.edit_entry, name="edit_entry"),
    path("random/", views.random_page, name="random_page"),
]

project1-wiki/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

project1-wiki/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

project1-wiki/wiki/encyclopedia/forms.py
from django import forms


class newEntryForm(forms.Form):
    title = forms.CharField(max_length=100)
    content = forms.CharField(widget=forms.Textarea)

project1-wiki/wiki/encyclopedia/views.py
import random

from django.db.models.expressions import NoneType
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from markdown2 import Markdown

from . import forms, util

markdowner = Markdown()


def index(request):
    return render(
        request,
        "encyclopedia/index.html",
        {
            "entries": util.list_entries(),
        },
    )


def content_page(request, title):
    content = util.get_entry(title)
    if content is None:
        return render(
            request,
            "encyclopedia/not_found.html",
            {
                "title": title,
            },
        )

    return render(
        request,
        "encyclopedia/content_page.html",
        {
            "title": title,
            "content": markdowner.convert(content),
        },
    )


def random_page(request):
    """
    open a random wiki page
    """
    print("View Exec")
    entries = util.list_entries()
    entry = random.choice(entries)
    return HttpResponseRedirect(
        reverse("encyclopedia:content_page", kwargs={"title": entry})
    )


def show_search_results(request):
    results = []
    query = ""
    if request.method == "POST":
        query = request.POST.get("q")
        results = util.get_search_results(query)

    if len(results) == 1 and query.lower() in [result.lower() for result in results]:
        # only redirect to a wiki page if the search query exactly(case-insensitive) matches the wiki page title
        return HttpResponseRedirect(
            reverse("encyclopedia:content_page", kwargs={"title": results[0]})
        )
    return render(
        request,
        "encyclopedia/search_results.html",
        {"results": results},
    )


def add_entry(request):
    """
    adds a new entry to local disk
    """
    form = forms.newEntryForm()
    if request.method == "POST":
        form = forms.newEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            existing_entries = util.list_entries()
            if title in existing_entries:
                form.add_error("title", "Title already exists, choose a different one")
            else:
                content = form.cleaned_data["content"]
                util.save_entry(title, content)
                return HttpResponseRedirect(
                    reverse(
                        "encyclopedia:content_page",
                        kwargs={
                            "title": title,
                        },
                    )
                )
    return render(
        request,
        "encyclopedia/add_entry.html",
        {
            "form": form,
        },
    )


def edit_entry(request):
    """
    edits an existing entry
    """
    if request.method == "POST":
        form = forms.newEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            util.save_entry(title, content)
            return HttpResponseRedirect(
                reverse(
                    "encyclopedia:content_page",
                    kwargs={
                        "title": title,
                    },
                )
            )
        return render(
            request,
            "encyclopedia/edit_entry.html",
            {
                "form": form,
            },
        )

    title = request.GET.get("title")
    return render(
        request,
        "encyclopedia/edit_entry.html",
        {
            "form": util.get_form_content(title),
        },
    )

project1-wiki/wiki/encyclopedia/templates/encyclopedia/add_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Add New Entry</h1>

    <form action="{% url 'encyclopedia:add_entry' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>

{% endblock %}

project1-wiki/wiki/encyclopedia/templates/encyclopedia/content_page.html
{% extends "encyclopedia/layout.html" %} 

{% block title %} 
Encyclopedia - {{title}}
{% endblock %} 

{% block body %}
<h1>{{title}}</h1>
{{content | safe}}

<form action="{% url 'encyclopedia:edit_entry' %}">
  <input type="submit" value="Edit Entry">
  <input type="hidden" name="title" value="{{title}}">
</form>
{% endblock %}

project1-wiki/wiki/encyclopedia/templates/encyclopedia/edit_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Edit Entry</h1>

    <form action="{% url 'encyclopedia:edit_entry' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Update">
    </form>

{% endblock %}

project1-wiki/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li> <a  href="wiki/{{entry}}">{{entry}}</a> </li>
        {% endfor %}
    </ul>

{% endblock %}

project1-wiki/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:show_search_results' %}" method="post">
                  {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:add_entry' %}">Create New Page</a>
                </div>
                <div>
                  <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

project1-wiki/wiki/encyclopedia/templates/encyclopedia/not_found.html
{% extends "encyclopedia/layout.html" %} 

{% block title%} 
Page Not Found 
{% endblock %} 

{% block body %}
<p>The content you are looking for was not found</p>
<a href="{% url 'encyclopedia:index' %}">Go Home</a>
{% endblock %}

project1-wiki/wiki/encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search Results</h1>

    <ul>
        {% for result in results %}
            <li> <a  href="wiki/{{result}}">{{result}}</a> </li>
        {% endfor %}
    </ul>

{% endblock %}